fuzz_level: 60
minted_blacklisted:
- coffeescript
- coffee-script
- restructuredtext
- c++
minted_mapping:
  Objective Caml: OCaml
  PHP/PHP: PHP
  ActionScript 2.0: ActionScript
  Apache Configuration: ApacheConf
  Pascal: Delphi
  Email: E-mail
  ANS-Forth94: Forth
  Fortran (Fixed Format): FortranFixed
  Fortran (Free Format): Fortran
  Godot: GDScript
  Inform: Inform 7
  INI Files: INI
  SQL (MySQL): MySQL
  Intel x86 (NASM): NASM
  Nim: Nimrod
  OV-Ray: POVRay
  Protobuf: Protocol Buffer
  RelaxNG-Compact: Relax-NG Compact
  RPM Spec: RPMSpec
  Ruby/Rails/RHTML: RHTML
  SML: Standard ML
  Tcl/Tk: Tcl
  LaTeX: Tex
  Todo.txt: Todotxt
  x.org Configuration: Xorg
  
lstlisting_mapping:
#  :ABAP (R/2 4.3, R/2 5.0, R/3 3.1, R/3 4.6C, R/3 6.10)
#  :ACM
#  :ACMscript
#  :ACSL
#  :Ada (2005, 83, 95)
#  :Algol (60, 68)
#  :Ant
#  :Assembler (Motorola68k, x86masm)
#  :Awk (gnu, POSIX)
#  :bash
#  :Basic (Visual)
#  :C (ANSI, Handel, Objective, Sharp)
#  :C++ (11, ANSI, GNU, ISO, Visual)
#  :Caml (light, Objective)
#  :CIL
#  :Clean
#  :Cobol (1974, 1985, ibm)
#  :Comal 80
#  :command.com (WinXP)
#  :Comsol
#  :csh
#  :Delphi
#  :Eiffel
#  :Elan
#  :elisp
#  :erlang
#  :Euphoria
#  :Fortran (03, 08, 77, 90, 95)
#  :GAP
#  :GCL
#  :Gnuplot
#  :Go
#  :hansl
#  :Haskell
#  :HTML
#  :IDL (empty, CORBA)
#  :inform
#  :Java (empty, AspectJ)
#  :JVMIS
#  :ksh
#  :Lingo
#  :Lisp (empty, Auto)
#  :LLVM
#  :Logo
#  :Lua (5.0, 5.1, 5.2, 5.3)
#  :make (empty, gnu)
#  :Mathematica (1.0, 11.0, 3.0, 5.2)
#  :Matlab
#  :Mercury
#  :MetaPost
#  :Miranda
#  :Mizar
#  :ML
#  :Modula-2
#  :MuPAD
#  :NASTRAN
#  :Oberon-2
#  :OCL (decorative, OMG)
#  :Octave
#  :OORexx
#  :Oz
#  :Pascal (Borland6, Standard, XSC)
#  :Perl
#  :PHP
#  :PL/I
#  :Plasm
#  :PostScript
#  :POV
#  :Prolog
#  :Promela
#  :PSTricks
#  :Python
#  :R
#  :Reduce
#  :Rexx (empty, VM/XA)
#  :RSL
#  :Ruby
#  :S (empty, PLUS)
#  :SAS
#  :Scala
#  :Scilab
#  :sh
#  :SHELXL
#  :Simula (67, CII, DEC, IBM)
#  :SPARQL
#  :SQL
#  :Swift
#  :TLA+
#  :tcl (empty, tk)
#  :TeX (AlLaTeX, common, LaTeX, plain, primitive)
#  :VBScript
#  :Verilog
#  :VHDL (empty, AMS)
#  :VRML (97)
#  :XML
#  :XSLT
